on: [push, pull_request]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
        if: github.ref == 'refs/heads/feature/pkgdown'
      - name: Query R package dependencies
        run: |
          install.packages("remotes")
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), "depends.Rds", version = 2)
        shell: Rscript {0}
      - name: Cache R package dependencies
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-
      - name: Install system dependencies
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning")
        shell: Rscript {0}
      - name: Install pkgdown and its dependencies
        if: github.ref == 'refs/heads/feature/pkgdown'
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev
          Rscript -e 'install_cran("curl")'
          Rscript -e 'remotes::install_dev("pkgdown")'
      - name: Deploy pkgdown website
        if: github.ref == 'refs/heads/feature/pkgdown'
        run: |
          remotes::install_local()
          pkgdown::deploy_to_branch(new_process = FALSE)
        shell: Rscript {0}
